export default Constants = {
  // NEXTPUBLICSUPABASE_URL: "http://192.168.1.40:8000",
  NEXTPUBLICSUPABASE_URL: "https://backend.delivery.maitretech.com",
  NEXTPUBLIC_ANON_KEY:
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ewogICJyb2xlIjogImFub24iLAogICJpc3MiOiAic3VwYWJhc2UiLAogICJpYXQiOiAxNzE3NDM5NDAwLAogICJleHAiOiAxODc1MjA1ODAwCn0.JEhCAjkG0KvAc7H6A4RkQNsF-lZW_OpYuT--XKHlAlw",
  NEXTPUBLIC_SERVICE_KEY:
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ewogICJyb2xlIjogInNlcnZpY2Vfcm9sZSIsCiAgImlzcyI6ICJzdXBhYmFzZSIsCiAgImlhdCI6IDE3MTc0Mzk0MDAsCiAgImV4cCI6IDE4NzUyMDU4MDAKfQ.Hk8mdy8SWwquw80R4X_sjVH6yLkrh5bZv0faH2_MSwc",
};
