export default Constants = {
  EXPOPUBLICSUPABASE_URL:process.env. EXPOPUBLICSUPABASE_URL,
  EXPONEXTPUBLIC_ANON_KEYL:process.env.EXPONEXTPUBLIC_ANON_KEY,
  NEXTPUBLIC_SERVICE_KEY: process.env.EXPO_PUBLIC_SERVICE_KEY,
};
