export default Constants = {
  EXPOPUBLICSUPABASE_URL:'http://192.168.1.40:8000',
  // EXPOPUBLICSUPABASE_URL:"https://backend.delivery.maitretech.com",
  EXPONEXTPUBLIC_ANON_KEY:'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE',
  NEXTPUBLIC_SERVICE_KEY: process.env.EXPO_PUBLIC_SERVICE_KEY,
};
